name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/book-backend ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/book-backend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/book-frontend ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/book-frontend
